app = "app-cool-violet-8335"
primary_region = "gru"

[build]

[http_service]
  force_https = false
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1