app = "app-cool-violet-8335"
primary_region = "gru"

[build]

[processes]
  app = "python3 coletor_blaze.py"

[[vm]]
  memory = "1024mb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  strategy = "immediate"