app = "app-cool-violet-8335"
primary_region = "gru"

[build]

# SEM http_service — não é uma aplicação web

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[processes]
  app = "python3 coletor_blaze.py"